# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main", "test_hypothesis" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:


jobs:
  build_matrix:
    strategy:
      matrix:
        os: [ubuntu-20.04, macos-12, windows-latest]
        
    runs-on: ${{ matrix.os }}
    env:
      app_name: app_${{ matrix.os }}_${{ github.run_number }}
    steps:
      - uses: actions/checkout@v3
      - name: Build
        run: g++ hello.cpp -o ${{ env.app_name }}
      - name: 'Upload Artifact'
        uses: actions/upload-artifact@v3
        with: 
          name: my-artifact-matrix
          path: ${{ env.app_name }}*
          # артефакты необязательно хранить всегда 
          retention-days: 5 


#   build_windows:
#     runs-on: windows-latest
#     steps:
#       - uses: actions/checkout@v3
#       - name: Build
#         run cl
#         # run: g++ hello.cpp -o ${{ env.app_name }}_${{ runner.os }}   
#       - name: 'Upload Artifact'
#         uses: actions/upload-artifact@v3
#         with: 
#           name: my-artifact
#           path: ${{ env.app_name }}_${{ runner.os }}
#           # артефакты необязательно хранить всегда 
#           retention-days: 5 

          
          
      
    
        
        
        
